### ISSUE TITLE
namespace tooltip

### ISSUE THREAD

**Issue by timelyportfolio** [TennisVisuals/updating-radar-chart#2]
I also spotted that tooltips are [assigned](https://github.com/TennisVisuals/updating-radar-chart/blob/master/radarChart.js#L130-L132) a class of `tooltip` which makes perfect sense, but unfortunately Bootstrap is not namespaced.  I avoid Bootstrap for this reason, but I know many folks rely on it.  When radar charts are on the same page as Bootstrap, the `.tooltip` conflicts and results in styling difficulties.

Would it be possible to namespace the radar chart tooltips with a more unique class, such as `radar-tooltip`?

Thanks again for this.

**Comment by TennisVisuals** [comment]
absolutely!  I will do an update by early next week.

**Comment by TennisVisuals** [comment]
added 'options.class' to set a prefix for several of the classes, including tooltips
