### ISSUE TITLE
events with more than one on a page

### ISSUE THREAD

**Issue by timelyportfolio** [TennisVisuals/updating-radar-chart#3]
Sorry to be a pest, but in [lines](https://github.com/TennisVisuals/updating-radar-chart/blob/master/radarChart.js#L885-L925) results in problems when more than one exists on a page.  In some cases this might be a "feature", but I think in general users might think of it as a bug.  Of course, you provide the ability to override this, so maybe you can leave as is.

Perhaps could you limit this to the containing element?

```
d3.selectAll("." + options.class + "RadarArea")
```

Probably should have used an animated GIF, but in the screenshot, you can see how hovering in the top chart (green in this case) causes the bottom chart areas to go transparent.

![image](https://cloud.githubusercontent.com/assets/837910/11569802/77d16710-99b9-11e5-9640-31b7222be483.png)

**Comment by TennisVisuals** [comment]
not at all!  Can you describe the problem a bit more? You're suggesting limiting the options.class option to the containing element?

**Comment by timelyportfolio** [comment]
I was just adding a screenshot when I saw your reply.  Hope it helps illustrate the issue.

**Comment by TennisVisuals** [comment]
I thought the selectAll statements were scoped to the enclosing element...  checking now

**Comment by timelyportfolio** [comment]
Since you do `d3.selectAll`, it will select everything in `document`.  To work as I am suggesting (again maybe not a good idea), you could do something like:

```
chart_node.selectAll(...)
```

**Comment by TennisVisuals** [comment]
ah, it's in the areaMouseover and areaMouseout where I do the d3.selectAll  Will fix that!

**Comment by timelyportfolio** [comment]
Let me know if uploading a bl.ock will help.  Thanks.

**Comment by TennisVisuals** [comment]
no, I've got it.

**Comment by timelyportfolio** [comment]
I think it is also in the `legendMouseover`.

**Comment by TennisVisuals** [comment]
yes

**Comment by TennisVisuals** [comment]
I think that's fixed it.  
I also played a bit with another niggly bit... have you noticed that you can toggle areas on and off by clicking on the Legend? Was hoping that I could .attr('display','none') the toggled areas so that hover events would work for lower areas, but alas.

**Comment by TennisVisuals** [comment]
let me know if the fix is really a fix and I will close this issue.  thanks.

**Comment by timelyportfolio** [comment]
That does fix.  Yes, I noticed the legend, but that will raise another issue.
