### ISSUE TITLE
legend click - right area but wrong circle

### ISSUE THREAD

**Issue by timelyportfolio** [TennisVisuals/updating-radar-chart#4]
Clicking on the legend entries causes the area to disappear as I would expect, but the circles to remain.  I'll inspect further to see what might be happening.  See below for what happens when I click the orange iPhone.  That might be the alas that you mention in #3.

![image](https://cloud.githubusercontent.com/assets/837910/11570866/14598478-99bf-11e5-948c-c7ded89f6c19.png)

**Comment by TennisVisuals** [comment]
hmm, I don't see that behavior in my application.  Is that when you have multiple instances?
Or, need to check, perhaps it's because my application sets specific colors for named data rows...

**Comment by TennisVisuals** [comment]
no, can't recreate it... yet

**Comment by TennisVisuals** [comment]
ah, set the chart.options(areas: { sort: false }) and see if that fixes it...

**Comment by TennisVisuals** [comment]
or, rather, masks the problem.

**Comment by timelyportfolio** [comment]
Ok, I'll dig deeper.  It does happen with just one chart.  Your suggestion `sort:false` does fix/mask the problem.

**Comment by timelyportfolio** [comment]
I think I also discovered a state issue with the legend.  I have clicked both Nokia and iPhone, but only the most recent click (Nokia) gets the circle icon in the legend.  However, the result in the chart is what I would expect.

![image](https://cloud.githubusercontent.com/assets/837910/11571507/5e8e8748-99c2-11e5-80e5-93e39dd67ec9.png)

**Comment by TennisVisuals** [comment]
yes, the 'state' icon change is something I have open with Susie Lu.  It's an issue with how d3-legend is implemented as Legends were never intended to be controls.

**Comment by TennisVisuals** [comment]
I think for the moment I will just disable the 'state' icon unless and until I get a workaround for it.
The sorting issue is a tricky bit of d3 coding, or at least something I don't fully understand as yet.

**Comment by TennisVisuals** [comment]
I think also that for the short term I will set the default for the areas.sort option to 'false'

Until I figure out the d3 contortions in this instance the problem will only surface if areas.sort is 'true' and legendClick is being used.

**Comment by timelyportfolio** [comment]
got it.  makes sense.

**Comment by timelyportfolio** [comment]
If I get a block of time, I'll try to help debug/fix.

**Comment by TennisVisuals** [comment]
we're traveling tomorrow so I may not have much time.  I've been playing with the sort and I'm not sure how useful it really is... especially since there is a legend to highlight the layers.  the sort was inspired by this: http://bl.ocks.org/micahstubbs/465725cdc547c7cc8491
Still, I would like to figure out how to get d3 to place the RadarCircles in the right order...

**Comment by timelyportfolio** [comment]
ok, sounds good.  I remember now that there is a similar sort feature in venn.js.  Maybe looking at https://github.com/benfred/venn.js/blob/master/src/layout.js#L292-L309 will help.

**Comment by TennisVisuals** [comment]
I think I've got the scent... probably due to an inconsistency in the use of data and _data
just need time to track it down...  but need to sleep now.

**Comment by TennisVisuals** [comment]
found it.  let me know if that works for you.

**Comment by timelyportfolio** [comment]
that works great!  Do you plan to change the default back to `sort:true`?

Thanks so much!

**Comment by TennisVisuals** [comment]
yes, changing back to default sort: true
fiddling a bit with legendClick toggle issue before I update

**Comment by TennisVisuals** [comment]
legendClick now toggles icons reliably.  also disabled hover for legend items which have been toggled. let me know if it all works as expected in your context.  thanks!

**Comment by timelyportfolio** [comment]
@TennisVisuals, thanks so much.  Legend does toggle as expected now.  But oh so close, when I have two, the areamouseover is disabled for both charts instead of just the one with a toggle legend.  I looked quickly and could not find the scope issue, but I'll keep looking.  Here is a screenshot to help explain.  I clicked to toggle Nokia in top chart which disables areamouseover also in the bottom chart.

![image](https://cloud.githubusercontent.com/assets/837910/11595679/4333d17e-9a76-11e5-8dc4-6c5d22e97a6e.png)

**Comment by TennisVisuals** [comment]
I will be able to take s look in about two hours

On Friday, December 4, 2015, timelyportfolio notifications@github.com
wrote:

> @TennisVisuals https://github.com/TennisVisuals, thanks so much. Legend
> does toggle as expected now. But oh so close, when I have two, the
> areamouseover is disabled for both charts instead of just the one with a
> toggle legend. I looked quickly and could not find the scope issue, but
> I'll keep looking. Here is a screenshot to help explain. I clicked to
> toggle Nokia in top chart which disables areamouseover also in the bottom
> chart.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/837910/11595679/4333d17e-9a76-11e5-8dc4-6c5d22e97a6e.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TennisVisuals/updating-radar-chart/issues/4#issuecomment-162022042
> .

## 

Charles Allen
http://www.linkedin.com/in/charlesaallen
http://tennisviz.blogspot.com
@TennisVisuals

**Comment by timelyportfolio** [comment]
no rush at all, I'll be on road in a little bit and prob will have very limited time to look over the weekend.  Hopefully, I can identify the lines in the next couple of minutes.

**Comment by TennisVisuals** [comment]
It is very simple.  I removed 'var' declaration for legend_toggle when
debugging and never replaced.

On Friday, December 4, 2015, timelyportfolio notifications@github.com
wrote:

> no rush at all, I'll be on road in a little bit and prob will have very
> limited time to look over the weekend. Hopefully, I can identify the lines
> in the next couple of minutes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TennisVisuals/updating-radar-chart/issues/4#issuecomment-162028313
> .

## 

Charles Allen
http://www.linkedin.com/in/charlesaallen
http://tennisviz.blogspot.com
@TennisVisuals

**Comment by timelyportfolio** [comment]
just found that :) Thanks

**Comment by TennisVisuals** [comment]
Can't make the fix on my phone but will do after dinner

On Friday, December 4, 2015, timelyportfolio notifications@github.com
wrote:

> no rush at all, I'll be on road in a little bit and prob will have very
> limited time to look over the weekend. Hopefully, I can identify the lines
> in the next couple of minutes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TennisVisuals/updating-radar-chart/issues/4#issuecomment-162028313
> .

## 

Charles Allen
http://www.linkedin.com/in/charlesaallen
http://tennisviz.blogspot.com
@TennisVisuals

**Comment by timelyportfolio** [comment]
I can change and submit pull if it helps.

**Comment by timelyportfolio** [comment]
but like I said, absolutely no rush on this.  Happy to help though in any way I can.

**Comment by TennisVisuals** [comment]
done.  thanks for YOUR help!

**Comment by timelyportfolio** [comment]
just getting back on the computer. Thanks so much.  I'll try to fully test again tonight and tomorrow.  I plan to make it the widget of the week, so maybe we can get some extra feedback and testing.

**Comment by TennisVisuals** [comment]
great.  I'm available for the next hour if you spot anything.
